apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    name: app
spec:
  ports:
  - name: mport
    protocol: TCP
    port: 8080
    nodePort: 32000
  selector:
    name: app
  type: NodePort